# Generated by Django 5.0.1 on 2024-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grabacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("duracion", models.DurationField(default=0)),
                ("convertida", models.BooleanField(default=False)),
                ("tipo_grabacion", models.IntegerField(default=1)),
            ],
        ),
    ]
