# Generated by Django 5.0.1 on 2024-02-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capturaweb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grabacion",
            name="convertida",
            field=models.BooleanField(default=False, verbose_name="Convertir"),
        ),
        migrations.AlterField(
            model_name="grabacion",
            name="tipo_grabacion",
            field=models.IntegerField(default=1, verbose_name="Tipo"),
        ),
    ]
