# Generated by Django 5.0.1 on 2024-02-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capturaweb", "0002_alter_grabacion_convertida_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatosGrabadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la capturadora"
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=100, verbose_name="Modelo de la placa"),
                ),
                (
                    "formato",
                    models.CharField(max_length=2, verbose_name="Formato de grabacion"),
                ),
                ("directorio_de_grabacion", models.CharField(max_length=100)),
            ],
        ),
    ]
